version: "3"
services:
  database:
    image: mysql:8.0
    container_name: mysql-movie
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3306:3306"
    env_file:
      - db.env
    networks:
    - movie_net_priv
    volumes:
      - mysqldata:/var/lib/mysql

  migrator:
    image: arigaio/atlas:1.1.5-alpine
    entrypoint: ["/bin/sh"]
    ## Sleep for 10 second to catch up with the db
    command: ["-c", "atlas migrate apply --dir file:///migrations --url $$HOSTURL"]
    container_name: movie-db-migrator
    restart: no
    volumes:
    - ../../migrations:/migrations
    env_file:
      - ./migrator.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - movie_net_priv

  app-backend: 
    build:
      context: ../../.
      dockerfile: Dockerfile
    image: kerolosayman308/movie-reservation:backend-1.0.0
    container_name: movie-backend
    env_file: ../../.env
    restart: always
    ports:
    - "8100:8000"
    depends_on:
    - database
    - migrator
    networks: 
    - movie_net_priv
    - movie_net_pub
    
networks:
  movie_net_priv:
    internal: true
  movie_net_pub:

volumes:
  mysqldata:
    driver: local
